language: ruby
cache: bundler

services:
  - redis-server

gemfile:
  - gemfiles/sidekiq_2.gemfile
  - gemfiles/sidekiq_3.gemfile
  - gemfiles/sidekiq_4.gemfile
  - gemfiles/sidekiq_5.gemfile

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

notifications:
  email: false
